/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misanidad2;

import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class VistaInicioSesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName());

    private Sistema sistema;
    
    /**
     * Creates new form VistaInicioSesion
     */
    public VistaInicioSesion(Sistema sistema) {
        this.sistema = sistema;
        setTitle("Iniciar sesión");
        initComponents();
        BotonIniciarSesion.requestFocusInWindow();
        UsuarioCampoTexto.setText("DNI / CIPA");
        UsuarioCampoTexto.setForeground(java.awt.Color.GRAY);
        setLocationRelativeTo(null);
    }
    
    private void login(){
        String id = UsuarioCampoTexto.getText();
        
        if (id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduce DNI o CIPA", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Usuario usuario = sistema.buscarUsuario(id.toUpperCase());
        
        if (usuario == null){
            JOptionPane.showMessageDialog(this, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!usuario.isActivo()){
            JOptionPane.showMessageDialog(this, "Usuario desactivado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        System.out.println("Usuario loggeado");
        
        switch(usuario.getTipo()){
            case TipoUsuario.PACIENTE:
                this.dispose();
                new VistaPaciente(sistema, (Paciente) usuario).setVisible(true);
                System.out.println("Loggeado como paciente");
                break;
            case TipoUsuario.MEDICO:
                this.dispose();
                new VistaMedico(sistema, (Medico) usuario).setVisible(true);
                System.out.println("Loggeado como medico");
                break;
            case TipoUsuario.PERSONAL_ADMINISTRACION:
                this.dispose();
                new VistaAdminCentroSalud(sistema, (PersonalAdministracion) usuario).setVisible(true);
                System.out.println("Loggeado como pers admin");
                break;
            case TipoUsuario.ADMINISTRADOR:
                this.dispose();
                new VistaAdministrador(sistema).setVisible(true);
                System.out.println("Loggeado como admin");
                break;
            default:
                System.out.println("Tipo no identificado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuarioCampoTexto = new javax.swing.JTextField();
        BotonIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UsuarioCampoTexto.setText("jTextField1");
        UsuarioCampoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuarioCampoTextoFocusGained(evt);
            }
        });
        UsuarioCampoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCampoTextoActionPerformed(evt);
            }
        });

        BotonIniciarSesion.setText("jButton1");
        BotonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Ver lista de usuarios");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotonIniciarSesion)
                        .addComponent(jLabel1)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(UsuarioCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonIniciarSesion)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioCampoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCampoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioCampoTextoActionPerformed

    private void BotonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSesionActionPerformed
        login();
    }//GEN-LAST:event_BotonIniciarSesionActionPerformed

    private void UsuarioCampoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioCampoTextoFocusGained
        UsuarioCampoTexto.setText("");
        UsuarioCampoTexto.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_UsuarioCampoTextoFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        new VistaTodosLosUsuarios(sistema).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Sistema sys = GestorArchivos.cargarSistema();
        Sistema sys = new Sistema();
        sys.datosPrueba(sys);
        
        GestorArchivos.guardarSistema(sys);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaInicioSesion(sys).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciarSesion;
    private javax.swing.JTextField UsuarioCampoTexto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
