package misanidad2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofbs
 */
import java.time.LocalDateTime; 
import java.time.ZoneId; 
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaEditarCita extends javax.swing.JFrame {
  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEditarCita.class.getName());

    /**
     * Creates new form VistaEditarCita
     */
    private Cita cita; 
    private Sistema sistema; 
    private VistaAdministrador ventana_anterior_admin;
    private VistaAdminCentroSalud ventana_anterior_centrosalud;
    
    public VistaEditarCita(Sistema sistema, Cita cita, VistaAdministrador v) {
        initComponents();
        this.cita = cita; 
        this.sistema = sistema; 
        ventana_anterior_admin = v;
        ventana_anterior_centrosalud = null;
        cargarDatos(); 
        setLocationRelativeTo(null);
    }
    
    public VistaEditarCita(Sistema sistema, Cita cita, VistaAdminCentroSalud ventana_anterior_centrosalud) {
        initComponents();
        this.cita = cita; 
        this.sistema = sistema; 
        ventana_anterior_admin = null;
        this.ventana_anterior_centrosalud = ventana_anterior_centrosalud;
        cargarDatos(); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkTelefonica = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardarCambios = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        txtCentro = new javax.swing.JTextField();
        txtMotivoCancelacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechahora_txt_field = new javax.swing.JTextField();
        seleccionPaciente = new javax.swing.JComboBox<>();
        seleccionMedico = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        seleccionEstado = new javax.swing.JComboBox<>();
        txtEspecialidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Paciente:");

        jLabel3.setText("Médico:");

        jLabel4.setText("Motivo:");

        jLabel5.setText("Centro:");

        checkTelefonica.setText("Telefónica");
        checkTelefonica.addActionListener(this::checkTelefonicaActionPerformed);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(this::btnGuardarCambiosActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel6.setText("Motivo cancelación:");

        txtMotivo.setText("txtMotivo");
        txtMotivo.addActionListener(this::txtMotivoActionPerformed);

        txtCentro.setText("txtCentro");
        txtCentro.addActionListener(this::txtCentroActionPerformed);

        txtMotivoCancelacion.addActionListener(this::txtMotivoCancelacionActionPerformed);

        jLabel7.setText("Fecha y hora:");

        fechahora_txt_field.setText("jTextField1");

        seleccionMedico.addActionListener(this::seleccionMedicoActionPerformed);

        jLabel9.setText("Estado");

        seleccionEstado.addActionListener(this::seleccionEstadoActionPerformed);

        txtEspecialidad.setText("Especialidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addGap(160, 160, 160)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(txtCentro))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(88, 88, 88)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seleccionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seleccionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seleccionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkTelefonica)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fechahora_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEspecialidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtMotivoCancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(seleccionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(seleccionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEspecialidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkTelefonica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(fechahora_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(seleccionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMotivoCancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTelefonicaActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        try{
            Paciente paciente = (Paciente) seleccionPaciente.getSelectedItem();
            Medico medico = (Medico) seleccionMedico.getSelectedItem();
            EstadoCita estado = (EstadoCita) seleccionEstado.getSelectedItem();
            String nuevoMotivo = txtMotivo.getText();
            String nuevoCentro = txtCentro.getText();
            boolean nuevaTelefonica = checkTelefonica.isSelected();
            String fecha_hora_str = fechahora_txt_field.getText();
            
            LocalDateTime fecha_hora = LocalDateTime.parse(fecha_hora_str, DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
            
            cita.setPaciente(paciente);
            cita.setMedico(medico);
            cita.setEstado(estado);
            cita.setMotivo(nuevoMotivo);
            cita.setCentro(nuevoCentro);
            cita.setFecha_hora(fecha_hora);
            if(medico.getEspecialidad() == Especialidad.GENERAL){
                cita.setTelefonica(nuevaTelefonica);
            }
            
            if(estado == EstadoCita.CANCELADA){
                cita.setMotivoCancelacion(txtMotivoCancelacion.getText());
                cita.setFechaCancelacion(LocalDateTime.now());
            }
            
            cita.getPaciente().agregarNotificacion(new Notificacion("Un administrador ha hecho una modificación en su cita ("+cita.getMotivo()+")."));
            
            JOptionPane.showMessageDialog(this, "Datos guardados.");
            GestorArchivos.guardarSistema(sistema);
            
            this.dispose();
            if(ventana_anterior_admin != null){
                ventana_anterior_admin.cargarTablaCitas(sistema);
            }
            
            if(ventana_anterior_centrosalud != null){
                ventana_anterior_centrosalud.cargarTablaCitas(sistema);
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void txtCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCentroActionPerformed

    private void txtMotivoCancelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoCancelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoCancelacionActionPerformed

    private void seleccionEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionEstadoActionPerformed
        // TODO add your handling code here:
        if(seleccionEstado.getSelectedItem() == EstadoCita.CANCELADA){
            txtMotivoCancelacion.setEditable(true);
            txtMotivoCancelacion.setText(cita.getMotivoCancelacion()); 
        }else{
            txtMotivoCancelacion.setEditable(false);
            txtMotivoCancelacion.setText("");
        }
    }//GEN-LAST:event_seleccionEstadoActionPerformed

    private void seleccionMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionMedicoActionPerformed
        // TODO add your handling code here:
        Medico m = (Medico) seleccionMedico.getSelectedItem();
        txtEspecialidad.setText("Especialidad:\n"+m.getEspecialidad());
        
        if(m.getEspecialidad() == Especialidad.GENERAL){
            checkTelefonica.setEnabled(true);
        } else {
            checkTelefonica.setEnabled(false);
            checkTelefonica.setSelected(false);
        }
    }//GEN-LAST:event_seleccionMedicoActionPerformed
    private void cargarDatos(){
        for(Paciente p : sistema.getTodosPacientes()){
            seleccionPaciente.addItem(p);
        }
        seleccionPaciente.setSelectedItem(cita.getPaciente());
        
        for(Medico m : sistema.getTodosMedicos()){
            seleccionMedico.addItem(m);
        }
        seleccionMedico.setSelectedItem(cita.getMedico());
        
        txtEspecialidad.setText("Especialidad:\n"+cita.getMedico().getEspecialidad());
        if(cita.getMedico().getEspecialidad() == Especialidad.GENERAL){
            checkTelefonica.setEnabled(true);
        } else {
            checkTelefonica.setEnabled(false);
            checkTelefonica.setSelected(false);
        }
        
        for(EstadoCita e : EstadoCita.values()){
            seleccionEstado.addItem(e);
        }
        seleccionEstado.setSelectedItem(cita.getEstado());
        
        txtMotivo.setText(cita.getMotivo());
        txtCentro.setText(cita.getCentro());
        checkTelefonica.setSelected(cita.isTelefonica());
        
        fechahora_txt_field.setText(cita.getFechaHora().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
        
        if(seleccionEstado.getSelectedItem() == EstadoCita.CANCELADA){
            txtMotivoCancelacion.setEditable(true);
            txtMotivoCancelacion.setText(cita.getMotivoCancelacion()); 
        }else{
            txtMotivoCancelacion.setEditable(false);
            txtMotivoCancelacion.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VistaEditarCita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JCheckBox checkTelefonica;
    private javax.swing.JTextField fechahora_txt_field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<EstadoCita> seleccionEstado;
    private javax.swing.JComboBox<Medico> seleccionMedico;
    private javax.swing.JComboBox<Paciente> seleccionPaciente;
    private javax.swing.JTextField txtCentro;
    private javax.swing.JLabel txtEspecialidad;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtMotivoCancelacion;
    // End of variables declaration//GEN-END:variables
}