/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misanidad2;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author sofbs
 */
public class VistaAdminCentroSalud extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdminCentroSalud.class.getName());

    /**
     * Creates new form VistaAdminCentroSalud
     */
    private Sistema sistema; 
    private PersonalAdministracion admin; 
    private VistaAdministrador ventanaAnterior; 
    public VistaAdminCentroSalud(Sistema sistema, PersonalAdministracion admin) {
        initComponents();
        this.sistema = sistema; 
        this.admin = admin; 
        
        setLocationRelativeTo(null); 
        cargarTablaPacientes(sistema); 
    }
    
    private Cita getCitaSeleccionada(){
        int fila = TablaCitas.getSelectedRow(); 
        if(fila == -1){
            JOptionPane.showMessageDialog(this,"Selecione una cita", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        int filaSel = TablaCitas.convertRowIndexToModel(fila); 
        List<Cita> lista = sistema.getCitasParaPaciente(getPacienteSeleccionado()); 
        if (filaSel >= lista.size()) return null; 
        
        return lista.get(filaSel); 
    }
    
    public void cargarTablaPacientes(Sistema sistema){
        String[] columnas = {"Nombre", "DNI", "CIPA", "Teléfono", "Dirección"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        for(Paciente p : sistema.getTodosPacientes()){
            Object[] fila = {p.getNombre(), p.getDni(), p.getCipa(), p.getTelefono(), p.getDireccion()};
            modelo.addRow(fila);
            
            TablaPacientes.setModel(modelo);
            TablaPacientes.setAutoCreateRowSorter(true);
        }
    }
    
    public Paciente getPacienteSeleccionado(){
        int filaVista = TablaPacientes.getSelectedRow();
        
        if (filaVista == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un usuario", "Aviso", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
        int filaModelo = TablaPacientes.convertRowIndexToModel(filaVista);
        return sistema.getTodosPacientes().get(filaModelo);
    }
    
    public void cargarTablaCitas(Sistema sistema){
        String[] columnas = {"Paciente", "Médico", "Estado", "Fecha", "Hora", "Motivo", "Fecha solicitud", "Centro", "Telefonica", "Motivo cancelación", "Fecha cancelación"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        for(Cita c : sistema.getCitasParaPaciente(getPacienteSeleccionado())){
            Object[] fila = {
                c.getPaciente().getNombre(),
                c.getMedico().getNombre(),
                c.getEstado(),
                c.getFechaHora().toLocalDate(),
                c.getFechaHora().toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm")),
                c.getMotivo(),
                c.getFechaSolicitud().toLocalDate()+" "+c.getFechaSolicitud().toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm")),
                c.getCentro(),
                c.isTelefonica() ? "Si" : "No",
                c.getEstado()==EstadoCita.CANCELADA ? c.getMotivoCancelacion() : "---",
                c.getEstado()==EstadoCita.CANCELADA ? c.getFechaCancelacion().toLocalDate()+" "+c.getFechaCancelacion().toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm")) : "---"
            };
            modelo.addRow(fila);
            
            TablaCitas.setModel(modelo);
            TablaCitas.setAutoCreateRowSorter(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaCitas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPacientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        jLabel1.setText("Administrador Centro de Salud");

        jLabel2.setText("Pacientes");

        btnEditar.setText("Editar paciente");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnVer.setText("Editar cita");
        btnVer.addActionListener(this::btnVerActionPerformed);

        TablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaCitas);

        TablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaPacientesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TablaPacientes);

        jLabel3.setText("Citas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVer))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnVer))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Paciente p = getPacienteSeleccionado(); 
        if(p == null) return; 
        
         new VistaEditarPaciente(sistema, p, this).setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        Cita c = getCitaSeleccionada();
        if(c == null) return;
        System.out.println(c.getPaciente());
        
        new VistaEditarCita(sistema, c, this).setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        new VistaInicioSesion(sistema).setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void TablaPacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacientesMousePressed
        // TODO add your handling code here:
        cargarTablaCitas(sistema);
    }//GEN-LAST:event_TablaPacientesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VistaAdminCentroSalud().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCitas;
    private javax.swing.JTable TablaPacientes;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
