/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misanidad2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alvar
 */
public class VistaTodosLosUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTodosLosUsuarios.class.getName());

    private Sistema sistema;
    
    /**
     * Creates new form VistaTodosLosUsuarios
     */
    public VistaTodosLosUsuarios(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        cargarTablaUsuarios(sistema);
    }
    
    private void cargarTablaUsuarios(Sistema sistema){
        String[] columnas = {"Nombre", "Rol", "DNI"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for(Usuario u : sistema.getTodosUsuarios()){
            Object[] fila = {
                u.getNombre(),
                u.getTipo(),
                u.getDni()
            };
            modelo.addRow(fila);
            
            TablaUsuarios.setModel(modelo);
            TablaUsuarios.setAutoCreateRowSorter(true);
        }
    }
    
    private void login(String dni){
        
        Usuario usuario = sistema.buscarUsuario(dni.toUpperCase());
                
        if (!usuario.isActivo()){
            JOptionPane.showMessageDialog(this, "Usuario desactivado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        System.out.println("Usuario loggeado");
        
        switch(usuario.getTipo()){
            case TipoUsuario.PACIENTE:
                this.dispose();
                new VistaPaciente(sistema, (Paciente) usuario).setVisible(true);
                System.out.println("Loggeado como paciente");
                break;
            case TipoUsuario.MEDICO:
                //abrirVentanaSanitario((Medico) usuario);
                System.out.println("Loggeado como medico");
                break;
            case TipoUsuario.PERSONAL_ADMINISTRACION:
                //abrirVentanaAdministracion((PersonalAdministracion) usuario);
                System.out.println("Loggeado como pers admin");
                break;
            case TipoUsuario.ADMINISTRADOR:
                //abrirVentanaAdministracion((Administrador) usuario);
                System.out.println("Loggeado como admin");
                break;
            default:
                System.out.println("Tipo no identificado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        BotonCerrar = new javax.swing.JButton();
        BotonIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaUsuarios);

        BotonCerrar.setText("Cerrar");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        BotonIniciarSesion.setText("Iniciar sesión como ...");
        BotonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonIniciarSesion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCerrar)
                    .addComponent(BotonIniciarSesion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        this.dispose();
        new VistaInicioSesion(sistema).setVisible(true);
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSesionActionPerformed
        int filaVista = TablaUsuarios.getSelectedRow();
        
        if (filaVista == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int filaModelo = TablaUsuarios.convertRowIndexToModel(filaVista);
        Usuario usr = sistema.getTodosUsuarios().get(filaModelo);
        String dni = usr.getDni();
        login(dni);
    }//GEN-LAST:event_BotonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaTodosLosUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonIniciarSesion;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
